### ISSUE TITLE
Spelling error in 03.markdown

### ISSUE THREAD

**Issue by alishasonawalla** [joannakl/ossd_s19#1]
In [this](https://github.com/joannakl/ossd_s19/blob/master/_includes/daily/03.markdown) markdown file under daily, I believe the sentence 'add your own question, and enter a number 1 next two it' should probably read 'add your own question, and enter a number 1 next _to_ it'

**Comment by joannakl** [comment]
@alishasonawalla good catch. I think by now it is probably replicated in a couple more places. Feel free to fix it, if you wish.

**Comment by alishasonawalla** [comment]
@joannakl Done! Made a PR to fix the issue (and a few more spelling errors) here https://github.com/joannakl/ossd_s19/pull/4 . Interestingly, the error hasn't been replicated elsewhere on the website :)
