### ISSUE TITLE
Closing Parentheses mistakenly compiled in Markdown

### ISSUE THREAD

**Issue by DaKoala** [joannakl/ossd_s19#17]
Link of the code: https://github.com/joannakl/ossd_s19/blob/master/slides/history.html#L37

Reproduction: https://cs.nyu.edu/~joannakl/ossd_s19/slides/history.html#2

The closing parentheses in the link is mistakenly compiled by Markdown as the end of link. Which leads to an incomplete link and a redundant closing parentheses displaying on the page. I find the way to fix it is replacing the closing parentheses with a URL encoding character `%29`.

Do you want me to fix it?

**Comment by DaKoala** [comment]
There is also a typo in the slides: https://github.com/joannakl/ossd_s19/blob/master/slides/history.html#L119

**Comment by joannakl** [comment]
@DaKoala  go for it
