### ISSUE TITLE
Wrong Dates for Classes #20-21

### ISSUE THREAD

**Issue by tojimjiang** [joannakl/ossd_s19#9]
These two classes in the "daily" portion of the website have incorrect dates listed.

They are listed as Tue/Thur, in early April.

**Comment by joannakl** [comment]
This issues should be claimed before people submit fixes.
Right now, there are two pull requests for it: #10 and #11

**Comment by alishasonawalla** [comment]
@joannakl Will be sure to do that in the future! I will go ahead and close my pull request, since both the PRs essentially do the same thing.

**Comment by joannakl** [comment]
fixed by #11
